# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('werewolf', '0002_auto_20161213_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game2User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
                ('character', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='character',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='content',
            field=models.TextField(default=b'{}'),
        ),
    ]
