# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0003_auto_20161214_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='userVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
                ('vote', models.IntegerField(default=-1)),
                ('day', models.IntegerField(default=0)),
            ],
        ),
    ]
